apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flask-app-demo-prd
  namespace: flux-system
spec:
  interval: 30s
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: flask-app-demo
      interval: 1ms
  targetNamespace: production
  values:
    namespace: production
    deployment:
      image: "oussamamaaroufi1/example-app-1"
      tag: "0.0.1"
    name: flask-demo-app-prd
  install:
    createNamespace: true  # Force the creatin of namespace if does not  exist in the cluster.
